### ISSUE TITLE
your meson version is too old 0.45.1 wanted 0.49.2 on Ubuntu 18.0.4

### ISSUE THREAD

**Issue by oneduality** [rdp/ffmpeg-windows-build-helpers#526]
Well above the version claimed required and this is the issue I get..  any thoughts?

**Comment by oneduality** [comment]
I fixed this by updating to ubuntu 20.x 

Now I get 

```
could not open '/mnt/x/ffmpeg/ffmpeg-windows-build-helpers/sandbox/win64/freetype-2.10.4/objs/ftexport.sym' for writing
make: *** [/mnt/x/ffmpeg/ffmpeg-windows-build-helpers/sandbox/win64/freetype-2.10.4/builds/exports.mk:68: /mnt/x/ffmpeg/ffmpeg-windows-build-helpers/sandbox/win64/freetype-2.10.4/objs/ftexport.sym] Error 3
make: *** Waiting for unfinished jobs....
```

This used to work fine until I pulled the latest version from github.. now I can't get it to build for the life of me..

**Comment by oneduality** [comment]
And yes the drive is rw
I'm running as root
There's terabytes of space available

**Comment by rdp** [comment]
Wsl is sometimes flakey.  Try in your home for or maybe create a virtual
box?

On Saturday, December 26, 2020, Lonnie <notifications@github.com> wrote:
> And yes the drive is rw
> I'm running as root
> There's terabytes of space available
>
> —
> You are receiving this because you are subscribed to this thread.
> Reply to this email directly, view it on GitHub, or unsubscribe.<
https://ci4.googleusercontent.com/proxy/pOcwAD_TG0pg1vnYcq4fakzeIrzdx6Fw4f-cHuUqjta0bpL_yYM9PCIGJU9XOUWi79naw33PdCz1EPCEdPBE75d_fSNqBn3Pxsd_k6T4QnqxE0SE_pmeCui7ynLPgipt6jS88Egs4tjSjGGhOmR7UCC1gisFGETBlK68IhygSgxm1SR54LLlyY-ZS0fbrkrJnlgyQdCMKH-cr_RdI5ifFai3s3rnyut6MQ1Gc91www=s0-d-e1-ft#https://github.com/notifications/beacon/AAADBUD2GXODUBDTRI4OFFLSW245BA5CNFSM4VJ2S4O2YY3PNVWWK3TUL52HS4DFVREXG43VMVBW63LNMVXHJKTDN5WW2ZLOORPWSZGOFTE5WEI.gif>

**Comment by zhlgh603** [comment]
I fixed it by updating meson.

> sudo apt-get clean
sudo apt-get update
sudo apt-get install python3-pip
sudo pip3 install meson

**Comment by rdp** [comment]
Using /mnt/xxx drives is sometimes flakey.  Reopen if issue still present from home dir, thanks!
