### ISSUE TITLE
Build Fails, tesseract not found using pkg-config

### ISSUE THREAD

**Issue by arrmo** [rdp/ffmpeg-windows-build-helpers#669]
Hi,

I see several items related to this, but not exactly seeing a fix 😢. May be me though! Building on Ubuntu 22.04 LTS, so pretty current. I see the error,
```
config options --pkg-config=pkg-config --pkg-config-flags=--static --extra-version=ffmpeg-windows-build-helpers --enable-version3 --disable-debug --disable-w32threads --arch=x86_64 --target-os=mingw32 --cross-prefix=/home/rmorris/Downloads/ffmpeg-windows-build-helpers/sandbox/cross_compilers/mingw-w64-x86_64/bin/x86_64-w64-mingw32- --enable-libcaca --enable-gray --enable-libtesseract --enable-fontconfig --enable-gmp --enable-libass --enable-libbluray --enable-libbs2b --enable-libflite --enable-libfreetype --enable-libfribidi --enable-libgme --enable-libgsm --enable-libilbc --enable-libmodplug --enable-libmp3lame --enable-libopencore-amrnb --enable-libopencore-amrwb --enable-libopus --enable-libsnappy --enable-libsoxr --enable-libspeex --enable-libtheora --enable-libtwolame --enable-libvo-amrwbenc --enable-libvorbis --enable-libwebp --enable-libzimg --enable-libzvbi --enable-libmysofa --enable-libopenjpeg --enable-libopenh264 --enable-libvmaf --enable-libsrt --enable-libxml2 --enable-opengl --enable-libdav1d --enable-cuda-llvm --enable-gnutls --enable-libaom --enable-nvenc --enable-nvdec --extra-libs=-lharfbuzz --extra-libs=-lm --extra-libs=-lshlwapi --extra-libs=-lmpg123 --extra-libs=-lpthread --extra-cflags=-DLIBTWOLAME_STATIC --extra-cflags=-DMODPLUG_STATIC --extra-cflags=-DCACA_STATIC --enable-amf --enable-libmfx --enable-gpl --enable-frei0r --enable-librubberband --enable-libvidstab --enable-libx264 --enable-libx265 --enable-avisynth --enable-libaribb24 --enable-libxvid --enable-libdavs2 --enable-libxavs2 --enable-libxavs --extra-cflags=-mtune=generic --extra-cflags=-O3 --enable-static --disable-shared --prefix=/home/rmorris/Downloads/ffmpeg-windows-build-helpers/sandbox/cross_compilers/mingw-w64-x86_64/x86_64-w64-mingw32 ./configure
ERROR: tesseract not found using pkg-config
```

Thoughts?

Thanks!

**Comment by FREEWING-JP** [comment]
I have same issue .
Windows 11 WSL Ubuntu 22.04
Windows 11 WSL Ubuntu 20.04
I don't know how to resolve 'ERROR: tesseract not found using pkg-config' .

But, You can build by disabling the Tesseract OCR feature.
https://github.com/rdp/ffmpeg-windows-build-helpers/issues/312#issuecomment-370247274

cf.
https://github.com/rdp/ffmpeg-windows-build-helpers/pull/668

**Comment by arrmo** [comment]
Thanks! Did that, now working ... sort of 😉. I find that,
1) Build for Win64 ... works, but then only works in CMD, not WSL - agreed?
2) Try to build Local Native, fails, with, `ERROR: libflite not found`

You see the same? I want to build a version that runs in WSL 😄 

Thanks again.

**Comment by rdp** [comment]
There was a PR for WSL 2 I just merged, try again?

**Comment by arrmo** [comment]
Sure, will do! 1, 2 ... or both?

Thanks!

**Comment by arrmo** [comment]
FYI, WSL 2 ... Local Native still fails. And build for Win64, back to,
```
ERROR: tesseract not found using pkg-config
```
Thanks!

**Comment by FREEWING-JP** [comment]
> 1 Build for Win64 ... works, but then only works in CMD, not WSL - agreed?

Yes . It for Windows CMD . not WSL .

> 2 Try to build Local Native, fails, with, ERROR: libflite not found

I don't care that . Because I need for Windows CMD . not WSL .

**Comment by arrmo** [comment]
Yes, understood - but right now, neither one successfully builds (on WSL) 😞 

Thanks!


PS: Still a bit confused why the Win64 build can't be executed from WSL.

**Comment by peterlus** [comment]
build_libwebp
-- do_git_checkout https://chromium.googlesource.com/webm/libwebp.git libwebp_git "origin/main"
++ do_git_checkout https://chromium.googlesource.com/webm/libwebp.git libwebp_git v1.2.4

it will solve this issue.

**Comment by arrmo** [comment]
That helps, thanks! Fixes that issue (so perhaps this needs to go into the code?) ... now I get 😆 
```
ERROR: amf requested but not found
```

Thinking this is a dependency I don't have in place (yet). Digging.

And still getting `ERROR: libflite not found` for the native build.

Thanks again.

**Comment by arrmo** [comment]
OK, got them both to the point of complaining about AMF ... 😆. And I do have that (AMF) copied to the system include directories! Hmmm.

**Comment by arrmo** [comment]
Found it! The fix for the amf error noted above. My (partial) diff,
```
-  do_git_checkout https://github.com/rdp/amf_headers.git amf_headers_git
+  #do_git_checkout https://github.com/rdp/amf_headers.git amf_headers_git
+  do_git_checkout https://github.com/GPUOpen-LibrariesAndSDKs/AMF.git amf_headers_git
```

I looked at the script, and it does what it's supposed to, related to [AMF](https://www.ffmpeg.org/general.html#AMD-AMF_002fVCE), but ... it's using a reduced size header set it seems, and the "[base](https://github.com/GPUOpen-LibrariesAndSDKs/AMF)" was modified just a few days ago. So I changed the script, pull the larger / full one, which is likely also aligned to ffmpeg ... and, voila! My build works now.

Perhaps use the full header repository?

Thanks!

**Comment by rdp** [comment]
The libwebp fixes the tesseract issue?

**Comment by arrmo** [comment]
Trying it right now - or should I set it to v1.3.0 (i.e. the most recent tag).

Also needing the AMF update above. Will confirm it all builds - would it help if I posted a diff then?

Thanks!

**Comment by arrmo** [comment]
OK, confirmed ... fixes the issue, but v1.3.0 fails (need v1.2.4). Here is my full diff, hope it helps (FYI, the AMF change is needed for amf fails, as noted above). Thanks!
```
diff --git a/cross_compile_ffmpeg.sh b/cross_compile_ffmpeg.sh
index bc051c7..5222717 100755
--- a/cross_compile_ffmpeg.sh
+++ b/cross_compile_ffmpeg.sh
@@ -830,7 +830,8 @@ build_amd_amf_headers() {
   # was https://github.com/GPUOpen-LibrariesAndSDKs/AMF.git too big
   # or https://github.com/DeadSix27/AMF smaller
   # but even smaller!
-  do_git_checkout https://github.com/rdp/amf_headers.git amf_headers_git
+  #do_git_checkout https://github.com/rdp/amf_headers.git amf_headers_git
+  do_git_checkout https://github.com/GPUOpen-LibrariesAndSDKs/AMF.git amf_headers_git

   cd amf_headers_git
     if [ ! -f "already_installed" ]; then
@@ -989,7 +990,7 @@ build_libpng() {
 }

 build_libwebp() {
-  do_git_checkout https://chromium.googlesource.com/webm/libwebp.git libwebp_git "origin/main"
+  do_git_checkout https://chromium.googlesource.com/webm/libwebp.git libwebp_git v1.2.4
   cd libwebp_git
     export LIBPNG_CONFIG="$mingw_w64_x86_64_prefix/bin/libpng-config --static" # LibPNG somehow doesn't get autodetected.
     generic_configure "--disable-wic"
```

**Comment by arrmo** [comment]
Looks to be aligned now to the diff above - agreed? So close it out?

Thanks!

**Comment by rdp** [comment]
Hopefully we got this, feel free to reopen if not :)
